# First workflow

name: First Workflow

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-app:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: echo message
        run: echo "Hello, from ubuntu-latest!"

  build-api:
    runs-on: windows-latest

    steps:
      - name: echo message
        run: echo "Hello, from windows-latest!"
  
  build-db:
    runs-on: macos-latest
    needs: build-app
    steps:
      - name: echo message
        run: echo "Hello, from macos-latest!"
