# First workflow

name: Secret Workflow

on:
  workflow_dispatch:

env:
  NODE_ENV: production
  API_URL: https://api.example.com

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: echo message
        run: echo "Azure key ${{ secrets.AZURE_KEYS }}"

  build-api:
    runs-on: windows-latest

    steps:
      - name: echo message
        run: echo "App key is ${{ secrets.APP_KEYS }}"
